version: "3.9"

services:
  web:
    build: .
    volumes:
        - "./:/usr/src/app"
    command: "npm start"
    ports:
      - 8080:8080

  localstack:
    image: localstack/localstack
    ports:
      - 4576:4576
    environment:
      - SERVICES=sqs
